* Downloaded Necessary .xpt files from,

    https://wwwn.cdc.gov/nchs/nhanes/continuousnhanes/default.aspx?Cycle=2021-2023

* Prepping the above collected data according to our requirements using python

In [1]:
# Required Module
import pandas as pd

**Demographics**

* File: DEMO_L.xpt
* Variables Information
https://wwwn.cdc.gov/nchs/nhanes/search/variablelist.aspx?Component=Demographics&Cycle=2021-2023
* Selected variables:
    'SEQN','RIAGENDR','RIDAGEYR'

In [2]:
demo = pd.read_sas("DEMO_L.xpt")[['SEQN','RIAGENDR','RIDAGEYR']]

In [3]:
demo.head()

       SEQN  RIAGENDR  RIDAGEYR
0  130378.0       1.0      43.0
1  130379.0       1.0      66.0
2  130380.0       2.0      44.0
3  130381.0       2.0       5.0
4  130382.0       1.0       2.0

In [4]:
demo.columns = ['SEQN','Gender','Age'] # Cols Rename

In [5]:
demo.SEQN = demo.SEQN.astype(int)

In [6]:
demo.head()

     SEQN  Gender   Age
0  130378     1.0  43.0
1  130379     1.0  66.0
2  130380     2.0  44.0
3  130381     2.0   5.0
4  130382     1.0   2.0

* Cols Data Validation

In [7]:
demo.Gender.unique()

array([1., 2.])

* Check Gender Notation in above link

In [8]:
round(demo.Age.describe())

count    11933.0
mean        38.0
std         26.0
min          0.0
25%         13.0
50%         37.0
75%         62.0
max         80.0
Name: Age, dtype: float64

In [9]:
demo.shape

(11933, 3)

**Dietary**

* Files: DR1IFF_L.xpt, DRXFCD_L.xpt
* Variables Information
https://wwwn.cdc.gov/nchs/nhanes/search/variablelist.aspx?Component=Dietary&Cycle=2021-2023
* Selected variables: 'SEQN','DR1_030Z','DR1CCMTX','DR1IFDCD','DR1IGRMS','DR1IKCAL','DR1IPROT','DR1ICARB','DR1ISUGR','DR1IFIBE','DR1ITFAT','DR1ICHOL'

* food and nutrients

In [10]:
dfn = pd.read_sas("DR1IFF_L.xpt")[['SEQN','DR1_030Z','DR1CCMTX','DR1IFDCD','DR1IGRMS','DR1IKCAL','DR1IPROT','DR1ICARB','DR1ISUGR','DR1IFIBE','DR1ITFAT','DR1ICHOL']]

In [11]:
dfn.head()

,SEQN,DR1_030Z,DR1CCMTX,DR1IFDCD,DR1IGRMS,DR1IKCAL,DR1IPROT,DR1ICARB,DR1ISUGR,DR1IFIBE,DR1ITFAT,DR1ICHOL
0,130378.0,7.0,5.397605e-79,94000100.0,120.0,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
1,130378.0,7.0,5.397605e-79,94000100.0,120.0,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
2,130378.0,1.0,5.397605e-79,92101000.0,300.0,3.000000e+00,3.600000e-01,5.397605e-79,5.397605e-79,5.397605e-79,6.000000e-02,5.397605e-79
3,130378.0,1.0,5.397605e-79,94000100.0,240.0,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
4,130378.0,2.0,4.000000e+00,83102000.0,4.9,2.700000e+01,1.100000e-01,1.600000e-01,1.400000e-01,5.397605e-79,2.830000e+00,2.000000e+00

In [12]:
# Handling floating point artifacts
dfn = dfn.applymap(lambda x: 0 if isinstance(x, (int, float)) and abs(x) < 1e-10 else x)
dfn.head()

,SEQN,DR1_030Z,DR1CCMTX,DR1IFDCD,DR1IGRMS,DR1IKCAL,DR1IPROT,DR1ICARB,DR1ISUGR,DR1IFIBE,DR1ITFAT,DR1ICHOL
0,130378.0,7.0,0.0,94000100.0,120.0,0.0,0.00,0.00,0.00,0.0,0.00,0.0
1,130378.0,7.0,0.0,94000100.0,120.0,0.0,0.00,0.00,0.00,0.0,0.00,0.0
2,130378.0,1.0,0.0,92101000.0,300.0,3.0,0.36,0.00,0.00,0.0,0.06,0.0
3,130378.0,1.0,0.0,94000100.0,240.0,0.0,0.00,0.00,0.00,0.0,0.00,0.0
4,130378.0,2.0,4.0,83102000.0,4.9,27.0,0.11,0.16,0.14,0.0,2.83,2.0

In [13]:
# Rename Cols
dfn.columns = ['SEQN','Occasion','DietType','FoodCode','Grams','Energy','Proteins','Carbs','Sugars','Fiber','Fat','Cholestrol']

In [14]:
dfn.head()

,SEQN,Occasion,DietType,FoodCode,Grams,Energy,Proteins,Carbs,Sugars,Fiber,Fat,Cholestrol
0,130378.0,7.0,0.0,94000100.0,120.0,0.0,0.00,0.00,0.00,0.0,0.00,0.0
1,130378.0,7.0,0.0,94000100.0,120.0,0.0,0.00,0.00,0.00,0.0,0.00,0.0
2,130378.0,1.0,0.0,92101000.0,300.0,3.0,0.36,0.00,0.00,0.0,0.06,0.0
3,130378.0,1.0,0.0,94000100.0,240.0,0.0,0.00,0.00,0.00,0.0,0.00,0.0
4,130378.0,2.0,4.0,83102000.0,4.9,27.0,0.11,0.16,0.14,0.0,2.83,2.0

In [15]:
# Converting Codes to int
dfn.SEQN = dfn.SEQN.astype(int)
dfn.DietType = dfn.DietType.astype(int)
dfn.Occasion = dfn.Occasion.astype(int)
dfn.FoodCode = dfn.FoodCode.astype(int)
dfn.head()

,SEQN,Occasion,DietType,FoodCode,Grams,Energy,Proteins,Carbs,Sugars,Fiber,Fat,Cholestrol
0,130378,7,0,94000100,120.0,0.0,0.00,0.00,0.00,0.0,0.00,0.0
1,130378,7,0,94000100,120.0,0.0,0.00,0.00,0.00,0.0,0.00,0.0
2,130378,1,0,92101000,300.0,3.0,0.36,0.00,0.00,0.0,0.06,0.0
3,130378,1,0,94000100,240.0,0.0,0.00,0.00,0.00,0.0,0.00,0.0
4,130378,2,4,83102000,4.9,27.0,0.11,0.16,0.14,0.0,2.83,2.0

* Working on Occassion, DietType & FoodNames

In [16]:
# Mappings from above url
combination_food_type = {
    0: "Non-combination food",
    1: "Beverage w/ additions",
    2: "Cereal w/ additions",
    3: "Bread/baked products w/ additions",
    4: "Salad",
    5: "Sandwiches",
    6: "Soup",
    7: "Frozen meals",
    8: "Ice cream/frozen yogurt w/ additions",
    9: "Dried beans and vegetable w/ additions",
    10: "Fruit w/ additions",
    11: "Tortilla products",
    12: "Meat, poultry, fish",
    13: "Lunchables®",
    14: "Chips w/ additions",
    15: "Baby Toddler Food and Infant Formula",
    90: "Other mixtures",
    ".": "Missing"
}
eating_occasion = {
    1: "Breakfast",
    2: "Lunch",
    3: "Dinner",
    4: "Supper",
    5: "Brunch",
    6: "Snack",
    7: "Drink",
    8: "Infant feeding",
    9: "Extended consumption",
    10: "Desayuno",
    11: "Almuerzo",
    12: "Comida",
    13: "Merienda",
    14: "Cena",
    15: "Entre comida",
    16: "Botana",
    17: "Bocadillo",
    18: "Tentempie",
    19: "Bebida",
    91: "Other",
    99: "Don’t know",
    ".": "Missing"
}

In [17]:
import warnings
warnings.filterwarnings("ignore")

dfn.DietType = dfn.DietType.replace(combination_food_type)
dfn.Occasion = dfn.Occasion.replace(eating_occasion)

In [18]:
dfn.head()

,SEQN,Occasion,DietType,FoodCode,Grams,Energy,Proteins,Carbs,Sugars,Fiber,Fat,Cholestrol
0,130378,Drink,Non-combination food,94000100,120.0,0.0,0.00,0.00,0.00,0.0,0.00,0.0
1,130378,Drink,Non-combination food,94000100,120.0,0.0,0.00,0.00,0.00,0.0,0.00,0.0
2,130378,Breakfast,Non-combination food,92101000,300.0,3.0,0.36,0.00,0.00,0.0,0.06,0.0
3,130378,Breakfast,Non-combination food,94000100,240.0,0.0,0.00,0.00,0.00,0.0,0.00,0.0
4,130378,Lunch,Salad,83102000,4.9,27.0,0.11,0.16,0.14,0.0,2.83,2.0

**USDA** food codes given along with description

In [19]:
foodinfo = pd.read_sas("DRXFCD_L.xpt")[['DRXFDCD','DRXFCSD']]

In [20]:
foodinfo

         DRXFDCD                                  DRXFCSD
0     11000000.0                           b'MILK, HUMAN'
1     11100000.0                             b'MILK, NFS'
2     11111000.0                           b'MILK, WHOLE'
3     11112110.0                b'MILK, REDUCED FAT (2%)'
4     11112210.0                    b'MILK, LOW FAT (1%)'
...          ...                                      ...
5427  99997810.0     b'VEGETABLES AS INGREDIENT IN CURRY'
5428  99997815.0     b'VEGETABLES AS INGREDIENT IN SOUPS'
5429  99997820.0     b'VEGETABLES AS INGREDIENT IN STEWS'
5430  99998130.0     b'SAUCE AS INGREDIENT IN HAMBURGERS'
5431  99998210.0  b'INDUSTRIAL OIL AS INGREDIENT IN FOOD'

[5432 rows x 2 columns]

In [21]:
foodinfo.columns = ['FoodCode','FoodDescription']

In [22]:
foodinfo.FoodCode = foodinfo.FoodCode.astype(int)

In [23]:
foodinfo

      FoodCode                          FoodDescription
0     11000000                           b'MILK, HUMAN'
1     11100000                             b'MILK, NFS'
2     11111000                           b'MILK, WHOLE'
3     11112110                b'MILK, REDUCED FAT (2%)'
4     11112210                    b'MILK, LOW FAT (1%)'
...        ...                                      ...
5427  99997810     b'VEGETABLES AS INGREDIENT IN CURRY'
5428  99997815     b'VEGETABLES AS INGREDIENT IN SOUPS'
5429  99997820     b'VEGETABLES AS INGREDIENT IN STEWS'
5430  99998130     b'SAUCE AS INGREDIENT IN HAMBURGERS'
5431  99998210  b'INDUSTRIAL OIL AS INGREDIENT IN FOOD'

[5432 rows x 2 columns]

In [24]:
# Cleaning Description
foodinfo.FoodDescription = foodinfo.FoodDescription.apply(lambda x: x.decode('utf-8') if isinstance(x, bytes) else x)

In [25]:
foodinfo.head()

   FoodCode         FoodDescription
0  11000000             MILK, HUMAN
1  11100000               MILK, NFS
2  11111000             MILK, WHOLE
3  11112110  MILK, REDUCED FAT (2%)
4  11112210      MILK, LOW FAT (1%)

* Mapping Food Description to above diet data based on Food Code

In [26]:
dfn = dfn.merge(foodinfo, on='FoodCode', how='left')

In [27]:
dfn.head()

,SEQN,Occasion,DietType,FoodCode,Grams,Energy,Proteins,Carbs,Sugars,Fiber,Fat,Cholestrol,FoodDescription
0,130378,Drink,Non-combination food,94000100,120.0,0.0,0.00,0.00,0.00,0.0,0.00,0.0,"WATER, TAP"
1,130378,Drink,Non-combination food,94000100,120.0,0.0,0.00,0.00,0.00,0.0,0.00,0.0,"WATER, TAP"
2,130378,Breakfast,Non-combination food,92101000,300.0,3.0,0.36,0.00,0.00,0.0,0.06,0.0,"COFFEE, BREWED"
3,130378,Breakfast,Non-combination food,94000100,240.0,0.0,0.00,0.00,0.00,0.0,0.00,0.0,"WATER, TAP"
4,130378,Lunch,Salad,83102000,4.9,27.0,0.11,0.16,0.14,0.0,2.83,2.0,CAESAR DRESSING

In [28]:
# De-Duplication
dfn = dfn.drop_duplicates().reset_index(drop=True)
dfn.shape

(97971, 13)

In [29]:
# grouping by Diet & Occassion
dfn = (
    dfn.groupby(['SEQN', 'Occasion', 'DietType','FoodDescription'])
       .agg({'Grams':'sum','Energy':'sum','Proteins':'sum','Carbs':'sum','Sugars':'sum','Fiber':'sum','Fat':'sum','Cholestrol':'sum'})
       .reset_index()
)
dfn.head()

,SEQN,Occasion,DietType,FoodDescription,Grams,Energy,Proteins,Carbs,Sugars,Fiber,Fat,Cholestrol
0,130378,Breakfast,Non-combination food,"COFFEE, BREWED",300.0,3.0,0.36,0.00,0.00,0.0,0.06,0.0
1,130378,Breakfast,Non-combination food,"WATER, TAP",240.0,0.0,0.00,0.00,0.00,0.0,0.00,0.0
2,130378,Dinner,Non-combination food,"ICE CREAM, VANILLA, WITH ADDITIONAL INGREDIENTS",125.0,302.0,4.59,38.14,31.67,1.3,14.70,48.0
3,130378,Dinner,Non-combination food,"PIZZA, CHEESE, WITH VEGETABLES, FROM RESTAURAN...",208.0,510.0,20.26,63.29,7.09,4.4,19.54,31.0
4,130378,Dinner,Non-combination food,"RICE, WHITE, WITH PEAS AND CARROTS, FAT ADDED",240.0,308.0,6.45,55.79,2.60,3.0,5.88,0.0

In [30]:
dfn.shape

(96680, 12)

* Cols Data Validation

In [31]:
dfn.Occasion.unique()

array(['Breakfast', 'Dinner', 'Drink', 'Lunch', 'Snack',
       'Extended consumption', 'Supper', 'Almuerzo', 'Bebida', 'Botana',
       'Merienda', 'Cena', 'Desayuno', 'Comida', 'Brunch',
       'Infant feeding', 'Tentempie', 'Entre comida', 'Bocadillo'],
      dtype=object)

In [32]:
dfn.DietType.unique()

array(['Non-combination food', 'Salad',
       'Dried beans and vegetable w/ additions', 'Sandwiches',
       'Chips w/ additions', 'Beverage w/ additions',
       'Cereal w/ additions', 'Tortilla products', 'Meat, poultry, fish',
       'Bread/baked products w/ additions', 'Other mixtures', 'Soup',
       'Ice cream/frozen yogurt w/ additions', 'Fruit w/ additions',
       'Frozen meals', 'Lunchables®',
       'Baby Toddler Food and Infant Formula'], dtype=object)

**Examination Data**
* Files: BMX_L.xpt, BPXO_L.xpt
* Variables Information
https://wwwn.cdc.gov/nchs/nhanes/search/variablelist.aspx?Component=Examination&Cycle=2021-2023
* Selected variables: SEQN & related

* BMI

In [33]:
bmx = pd.read_sas("BMX_L.xpt")[['SEQN','BMXBMI']]

In [34]:
bmx

          SEQN  BMXBMI
0     130378.0    27.0
1     130379.0    33.5
2     130380.0    29.7
3     130381.0    23.8
4     130382.0     NaN
...        ...     ...
8855  142306.0    15.4
8856  142307.0     NaN
8857  142308.0    26.4
8858  142309.0    25.5
8859  142310.0    27.6

[8860 rows x 2 columns]

In [35]:
bmx.columns = ['SEQN','BMI']

In [36]:
bmx.SEQN = bmx.SEQN.astype(int)
bmx.head()

     SEQN   BMI
0  130378  27.0
1  130379  33.5
2  130380  29.7
3  130381  23.8
4  130382   NaN

* BP

In [37]:
bp = pd.read_sas("BPXO_L.xpt")[['SEQN','BPXOSY1','BPXOSY2','BPXOSY3','BPXODI1','BPXODI2','BPXODI3']]

In [38]:
bp.head()

       SEQN  BPXOSY1  BPXOSY2  BPXOSY3  BPXODI1  BPXODI2  BPXODI3
0  130378.0    135.0    131.0    132.0     98.0     96.0     94.0
1  130379.0    121.0    117.0    113.0     84.0     76.0     76.0
2  130380.0    111.0    112.0    104.0     79.0     80.0     76.0
3  130386.0    110.0    120.0    115.0     72.0     74.0     75.0
4  130387.0    143.0    136.0    145.0     76.0     74.0     78.0

In [39]:
# Taking Average from Three Readings
bp['Systolic_bp'] = round((bp['BPXOSY1']+bp['BPXOSY2']+bp['BPXOSY3'])/3)
bp['Diastolic_bp'] = round((bp['BPXODI1']+bp['BPXODI2']+bp['BPXODI3'])/3)

In [40]:
bp.head()

,SEQN,BPXOSY1,BPXOSY2,BPXOSY3,BPXODI1,BPXODI2,BPXODI3,Systolic_bp,Diastolic_bp
0,130378.0,135.0,131.0,132.0,98.0,96.0,94.0,133.0,96.0
1,130379.0,121.0,117.0,113.0,84.0,76.0,76.0,117.0,79.0
2,130380.0,111.0,112.0,104.0,79.0,80.0,76.0,109.0,78.0
3,130386.0,110.0,120.0,115.0,72.0,74.0,75.0,115.0,74.0
4,130387.0,143.0,136.0,145.0,76.0,74.0,78.0,141.0,76.0

In [41]:
bp = bp[['SEQN','Systolic_bp','Diastolic_bp']]

In [42]:
bp.head()

       SEQN  Systolic_bp  Diastolic_bp
0  130378.0        133.0          96.0
1  130379.0        117.0          79.0
2  130380.0        109.0          78.0
3  130386.0        115.0          74.0
4  130387.0        141.0          76.0

In [43]:
bp.SEQN = bp.SEQN.astype(int)
bp.head()

     SEQN  Systolic_bp  Diastolic_bp
0  130378        133.0          96.0
1  130379        117.0          79.0
2  130380        109.0          78.0
3  130386        115.0          74.0
4  130387        141.0          76.0

**Laboratory**
* Files:TCHOL_L.xpt
* Variables Info: https://wwwn.cdc.gov/nchs/nhanes/search/variablelist.aspx?Component=Laboratory&Cycle=2021-2023
* Selected Variables: SEQN & Related

* Cholestrol

In [44]:
ch = pd.read_sas("TCHOL_L.xpt")[['SEQN','LBXTC']]

In [45]:
ch.head()

       SEQN  LBXTC
0  130378.0  264.0
1  130379.0  214.0
2  130380.0  187.0
3  130386.0  183.0
4  130387.0  203.0

In [46]:
ch.columns = ['SEQN','Cholesterol']
ch.SEQN = ch.SEQN.astype(int)
ch.head()

     SEQN  Cholesterol
0  130378        264.0
1  130379        214.0
2  130380        187.0
3  130386        183.0
4  130387        203.0

**Questionarrie**
* Files: DIQ_L.xpt, DPQ_L.xpt
* Variables Info: https://wwwn.cdc.gov/nchs/nhanes/search/variablelist.aspx?Component=Questionnaire&Cycle=2021-2023
* Selected: SEQN & Related

* Diabetes

In [47]:
db = pd.read_sas("DIQ_L.xpt")[['SEQN','DIQ010']]

In [48]:
db.columns = ['SEQN','Diabetes']
db.SEQN = db.SEQN.astype(int)
db.head()

     SEQN  Diabetes
0  130378       2.0
1  130379       2.0
2  130380       1.0
3  130381       2.0
4  130382       2.0

In [49]:
db.Diabetes.unique()

array([ 2.,  1.,  3., nan,  9.])

* Mental Health

In [50]:
# Over The Last Two Weeks
mh = pd.read_sas("DPQ_L.xpt")

In [51]:
mh

,SEQN,DPQ010,DPQ020,DPQ030,DPQ040,DPQ050,DPQ060,DPQ070,DPQ080,DPQ090,DPQ100
0,130378.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,130379.0,5.397605e-79,5.397605e-79,1.000000e+00,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
2,130380.0,5.397605e-79,5.397605e-79,1.000000e+00,1.000000e+00,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
3,130386.0,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,1.000000e+00,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
4,130387.0,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,NaN
...,...,...,...,...,...,...,...,...,...,...,...
6332,142305.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6333,142307.0,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,NaN
6334,142308.0,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,NaN
6335,142309.0,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,NaN
6336,142310.0,5.397605e-79,5.397605e-79,5.397605e-79,1.000000e+00,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79

# By the observation of Variables info
mh.columns = [['SEQN','Little interest in doing things','Feeling down, depressed, or hopeless',
              'Trouble sleeping or sleeping too much','Feeling tired or having little energy',
              'Poor appetite or overeating','Feeling bad about yourself','Trouble concentrating on things',
              'Moving or speaking slowly or too fast','Thought you would be better off dead','Difficulty these problems have caused']]
              
stress:DPQ010,DPQ050,DPQ070,DPQ080,DPQ100
sleep:DPQ030
mood:DPQ020,DPQ040,DPQ060,DPQ090

# Working on above in Modeling

In [52]:
mh.SEQN = mh.SEQN.astype(int)
mh.head()

,SEQN,DPQ010,DPQ020,DPQ030,DPQ040,DPQ050,DPQ060,DPQ070,DPQ080,DPQ090,DPQ100
0,130378,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,130379,5.397605e-79,5.397605e-79,1.000000e+00,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
2,130380,5.397605e-79,5.397605e-79,1.000000e+00,1.000000e+00,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
3,130386,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,1.000000e+00,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
4,130387,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,NaN

In [53]:
# Handling floating point artifacts
mh = mh.applymap(lambda x: 0 if isinstance(x, (int, float)) and abs(x) < 1e-10 else x)
mh.head()

,SEQN,DPQ010,DPQ020,DPQ030,DPQ040,DPQ050,DPQ060,DPQ070,DPQ080,DPQ090,DPQ100
0,130378,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,130379,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,130380,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,130386,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,130387,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

* Considering above into three major categories upon observation

In [54]:
stress_cols = ['DPQ010', 'DPQ050', 'DPQ070', 'DPQ080', 'DPQ100']
sleep_cols = ['DPQ030']
mood_cols = ['DPQ020', 'DPQ040', 'DPQ060', 'DPQ090']

In [55]:
mh['Stress'] = round(mh[stress_cols].mean(axis=1))
mh['Sleep'] = round(mh[sleep_cols].mean(axis=1))
mh['Mood'] = round(mh[mood_cols].mean(axis=1))

In [56]:
mh = mh[['SEQN', 'Stress', 'Sleep', 'Mood']]

* Col data validation

In [57]:
for col in mh.columns[1:]:
    print(col, mh[col].unique())

Stress [nan  0.  3.  1.  2.  4.  5.]
Sleep [nan  1.  0.  3.  2.  9.  7.]
Mood [nan  0.  2.  1.  3.  4.  7.]

* According to variable description in above url we have 0,1,2,3,7,9 only
    - replacing others to close value

In [58]:
mh.replace({4.0:7.0, 5.0:7.0}, inplace=True)

In [59]:
for col in mh.columns[1:]:
    print(col, mh[col].unique())

Stress [nan  0.  3.  1.  2.  7.]
Sleep [nan  1.  0.  3.  2.  9.  7.]
Mood [nan  0.  2.  1.  3.  7.]

In [60]:
mh.head()

     SEQN  Stress  Sleep  Mood
0  130378     NaN    NaN   NaN
1  130379     0.0    1.0   0.0
2  130380     0.0    1.0   0.0
3  130386     0.0    0.0   0.0
4  130387     0.0    0.0   0.0

**Final Merge**

In [61]:
demo.shape, bmx.shape, bp.shape, ch.shape, db.shape, mh.shape, dfn.shape

((11933, 3),
 (8860, 2),
 (7801, 3),
 (8068, 2),
 (11744, 2),
 (6337, 4),
 (96680, 12))

In [62]:
# Merge Commands: Picking SEQN Matched rows only -> Inner
data = demo.copy()
data = pd.merge(data, bmx, on='SEQN', how='inner')
data = pd.merge(data, bp, on='SEQN', how='inner')
data = pd.merge(data, ch, on='SEQN', how='inner')
data = pd.merge(data, db, on='SEQN', how='inner')
data = pd.merge(data, mh, on='SEQN', how='inner')
data = pd.merge(data, dfn, on='SEQN', how='inner')

print(f'combined dataset size : {data.shape}')

combined dataset size : (73778, 22)

In [63]:
data.head()

,SEQN,Gender,Age,BMI,Systolic_bp,Diastolic_bp,Cholesterol,Diabetes,Stress,Sleep,...,DietType,FoodDescription,Grams,Energy,Proteins,Carbs,Sugars,Fiber,Fat,Cholestrol
0,130378,1.0,43.0,27.0,133.0,96.0,264.0,2.0,NaN,NaN,...,Non-combination food,"COFFEE, BREWED",300.0,3.0,0.36,0.00,0.00,0.0,0.06,0.0
1,130378,1.0,43.0,27.0,133.0,96.0,264.0,2.0,NaN,NaN,...,Non-combination food,"WATER, TAP",240.0,0.0,0.00,0.00,0.00,0.0,0.00,0.0
2,130378,1.0,43.0,27.0,133.0,96.0,264.0,2.0,NaN,NaN,...,Non-combination food,"ICE CREAM, VANILLA, WITH ADDITIONAL INGREDIENTS",125.0,302.0,4.59,38.14,31.67,1.3,14.70,48.0
3,130378,1.0,43.0,27.0,133.0,96.0,264.0,2.0,NaN,NaN,...,Non-combination food,"PIZZA, CHEESE, WITH VEGETABLES, FROM RESTAURAN...",208.0,510.0,20.26,63.29,7.09,4.4,19.54,31.0
4,130378,1.0,43.0,27.0,133.0,96.0,264.0,2.0,NaN,NaN,...,Non-combination food,"RICE, WHITE, WITH PEAS AND CARROTS, FAT ADDED",240.0,308.0,6.45,55.79,2.60,3.0,5.88,0.0

In [64]:
data.dtypes

SEQN                 int32
Gender             float64
Age                float64
BMI                float64
Systolic_bp        float64
Diastolic_bp       float64
Cholesterol        float64
Diabetes           float64
Stress             float64
Sleep              float64
Mood               float64
Occasion            object
DietType            object
FoodDescription     object
Grams              float64
Energy             float64
Proteins           float64
Carbs              float64
Sugars             float64
Fiber              float64
Fat                float64
Cholestrol         float64
dtype: object

In [65]:
data.to_csv("HealthMetrics+MentalHealth+DietNutrient.csv", index=False)